strictness: veryhigh
test-warnings: true
doc-warnings: true
max-line-length: 88

pydocstyle:
  disable:
    - D203
    - D213

pyroma:
  run: true

vulture:
  run: true

mypy:
  run: true

bandit:
  run: true

pyright:
  run: true
