name: Perform a semantic release on the main branch
on:
  workflow_dispatch: # only manual publishing for now.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Create a virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m venv env
          source env/bin/activate
      - name: Install the package dependencies
        run: python -m pip install .
      - name: Publish the next semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_SEMANTIC_RELEASE }}
        run: |
          semantic-release version && semantic-release publish
      - name: Run the tests to verify the consumer contract
        env:
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        run: pytest
